# Generated by Django 4.0.4 on 2022-10-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, default=' ', null=True)),
                ('precio', models.FloatField(default=0)),
                ('product_img1', models.ImageField(default='productos_images/blank.png', upload_to='productos_images')),
                ('product_img2', models.ImageField(default='productos_images/blank.png', upload_to='productos_images')),
                ('product_img3', models.ImageField(default='productos_images/blank.png', upload_to='productos_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_api.categoria')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
