# Generated by Django 4.0.4 on 2022-10-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='about',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='product_img2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='product_img3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='product_name',
        ),
    ]
