# Generated by Django 4.0.4 on 2022-10-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_remove_producto_about_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(default='productos_images/blank.png', upload_to='categories_images'),
        ),
    ]
