# Generated by Django 4.0.4 on 2022-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0003_categoria_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
