# Generated by Django 4.0.4 on 2022-10-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0004_categoria_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_es',
        ),
        migrations.AddField(
            model_name='categoria',
            name='description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categoria',
            name='description_turk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_en',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_turk',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
