# Generated by Django 4.0.4 on 2022-10-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0005_rename_description_categoria_description_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
