# Generated by Django 4.0.4 on 2022-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default=' ')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('certificado', models.ImageField(blank=True, default='productos_images/blank.png', null=True, upload_to='info_company')),
                ('img', models.ImageField(blank=True, default='productos_images/blank.png', null=True, upload_to='info_company')),
            ],
        ),
    ]
