# Generated by Django 4.0.4 on 2022-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email_contact',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
