# Generated by Django 4.0.4 on 2022-10-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_email_contact_alter_about_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='about_en',
        ),
        migrations.AddField(
            model_name='about',
            name='about_es',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='about',
            name='about_turk',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
